name: Gatsby Publish

on:
  push:
    branches:
      - master
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        env: 
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
