name: Merge PR
on:
  pull_request:
    types: [closed]
jobs:
  merge-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 10.15.3
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Github Page
        run: npm run deploy
